# Generated by Django 5.1.7 on 2025-04-26 09:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_emi'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi',
            name='due_date_time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emi',
            name='due_date',
            field=models.IntegerField(),
        ),
    ]
