# Generated by Django 5.1.7 on 2025-04-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_emi_due_date_time_alter_emi_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emi',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='emi',
            name='due_date_time',
            field=models.DateTimeField(),
        ),
    ]
