# Generated by Django 5.1.7 on 2025-04-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_emi_category_alter_emi_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='expense',
            name='opening_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
