# Generated by Django 5.1.7 on 2025-04-26 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_bank_opening_balance_expense_opening_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='opening_balance',
        ),
    ]
