# Generated by Django 5.1.7 on 2025-05-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_investmenttype_broker_investment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['-updated_at'], 'verbose_name_plural': 'Banks'},
        ),
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ['-purchase_date'], 'verbose_name_plural': 'Investments'},
        ),
        migrations.AddField(
            model_name='investment',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee (₹)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('JPY', 'Japanese Yen (¥)'), ('AUD', 'Australian Dollar (A$)'), ('CAD', 'Canadian Dollar (C$)'), ('SGD', 'Singapore Dollar (S$)')], default='INR', max_length=3),
        ),
    ]
